query allTenants {
  tenants {
    id
    description
    color
    modules {
      name
      settings {
        name
        value
      }
    }
    roleMappings{
      role
      claimValue
      environmentId
    }
    emails
  }
}
