#import "./Fragments.gql"

mutation saveIdentityServerGroup($input: SaveIdentityServerGroupInput!) {
  saveIdentityServerGroup(input: $input) {
    serverGroup {
      ...IdentityServerGroup
    }
  }
}
