query dependencies($input: GetDependenciesInput!) {
  dependencies(input: $input) {
    apiScopes {
      title
      id
    }
    identityResources {
      title
      id
    }
    apiResources {
      title
      id
    }
    clients {
      title
      id
    }
    personalAccessTokens {
      title
      id
    }
  }
}
