mutation requestToken($input: RequestClientCredentialsTokenInput!) {
  requestToken(input: $input) {
    result {
      accessToken {
        token
      }
      isSuccess
      errorMessage
    }
  }
}
