#import "./Fragments.gql"

mutation addEnvironmentToApplication($input: AddEnvironmentToApplicationInput!) {
  addEnvironmentToApplication(input: $input) {
    application {
      ...Application
    }
  }
}
