#import "./ApplicationFragment.gql"
#import "./ClientInfoFragment.gql"

mutation CreateApplication($input: CreateApplicationInput!) {
  createApplication(input: $input) {
    application {
      ...Application
    }
    clients {
      ...ClientInfo
    }
  }
}
