fragment Application on Application {
  id
  tenant
  name
  title
  templateId
  template{
    id
    name
  }
  apiScopes
  identityScopes
  clientIds
  allowedGrantTypes
  clientIds
  clients {
    id
    clientId
    name
    environments
  }
  userClaimRules{
    id
    name
  }
  redirectUris
  tenantInfo{
    color
    id
  }   
}
