#import "./ApplicationFragment.gql"

mutation removeClientFromApplication($input: RemoveClientInput!) {
  removeClientFromApplication(input: $input) {
    application {
      ...Application
    }
  }
}
