#import "./Fragments.gql"

mutation addSecretToPersonalAccessToken($input: AddSecretPersonalAccessTokenInput!) {
  addSecretToPersonalAccessToken(input: $input) {
    token {
      ...PersonalAccessToken
    }
    secret
  }
}
