#import "./Fragments.gql"

mutation createPersonalAccessToken($input: CreatePersonalAccessTokenInput!) {
  createPersonalAccessToken(input: $input) {
    token {
      ...PersonalAccessToken
    }
  }
}
