#import "./Fragments.gql"

mutation removeSecretToPersonalAccessToken($input: RemoveSecretPersonalAccessTokenInput!) {
  removeSecretOfPersonalAccessToken(input: $input) {
    token {
      ...PersonalAccessToken
    }
  }
}
