#import "./Fragments.gql"
query SearchPersonalAccessTokens($input: SearchPersonalAccessTokensInput!) {
  searchPersonalAccessTokens(input: $input) {
    hasMore
    items {
      id
      userName
      environmentId
      createdAt
      tenant
      tenantInfo {
        color
        id
      }
    }
  }
}
