#import "./Fragments.gql"
query SearchPersonalAccessTokens($input: SearchPersonalAccessTokensInput!) {
  searchPersonalAccessTokens(input: $input) {
    hasMore
    items {
      ... PersonalAccessToken
    }
  }
}
