#import "./Fragments.gql"
mutation savePersonalAccessToken($input: UpdatePersonalAccessTokenInput!) {
  updatePersonalAccessToken(input: $input) {
    token {
      ...PersonalAccessToken
    }
  }
}
