name: Pull Request

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Build, Test and Sonar
        uses: swisslife-oss/actions/pull-request@main
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_project_key: 'SwissLife-OSS_IdOps'
          sonar_project_name: "IdOps"
          pr_number: ${{ github.event.pull_request.number }}
          pr_source_branch: ${{ github.head_ref }}
          pr_target_branch: ${{ github.base_ref }}
          github_repository: ${{ github.repository }}
          sonar_exclusions: ${{ vars.SONAR_EXCLUSIONS }}

  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version-file: 'src/UI/package.json'
          cache: 'yarn'
          cache-dependency-path: 'src/UI/yarn.lock'
      - name: Build UI
        run: |
          yarn --cwd src/UI
          yarn --cwd src/UI build
          rm -rf src/Server/src/AspNet/UI
          mkdir src/Server/src/AspNet/UI/
          cp -rf src/UI/dist/* src/Server/src/AspNet/UI
        shell: bash
